DROP TABLE TABLE_2 CASCADE CONSTRAINTS;

CREATE TABLE TABLE_2
(
  SABUN         CHAR(8 BYTE),
  ACAD_ABILITY  CHAR(4 BYTE),
  MAJOR_STUDY   VARCHAR2(10 BYTE),
  GRAT_YM       CHAR(6 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



DROP TABLE TABLE_3 CASCADE CONSTRAINTS;

CREATE TABLE TABLE_3
(
  ACAD_ABILITY  CHAR(4 BYTE),
  GRADE_NUM     NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE INSA_RECT_NOTICE
 DROP PRIMARY KEY CASCADE;

DROP TABLE INSA_RECT_NOTICE CASCADE CONSTRAINTS;

CREATE TABLE INSA_RECT_NOTICE
(
  RECT_REG_NO       VARCHAR2(15 BYTE)           NOT NULL,
  PJT_GBN           CHAR(3 BYTE),
  RECV_START_DAY    DATE,
  RECV_END_DAY      DATE,
  ANNOCM_TITLE      VARCHAR2(200 BYTE),
  PJT_NAME          VARCHAR2(250 BYTE),
  RECTM_POINT       VARCHAR2(500 BYTE),
  PUT_START_DAY     DATE,
  PUT_END_DAY       DATE,
  CARRIER_GBN_CODE  CHAR(3 BYTE),
  ACAD_GBN_CODE     VARCHAR2(2 BYTE),
  PROG_STATE_CODE   CHAR(3 BYTE),
  SUPP_AREA_CODE    VARCHAR2(3 BYTE),
  CMM_PER_QUAL      VARCHAR2(250 BYTE),
  REMARK            VARCHAR2(250 BYTE),
  EXHIBIT           VARCHAR2(250 BYTE),
  RECV_WAY          VARCHAR2(250 BYTE),
  PROG_WAY          VARCHAR2(250 BYTE),
  ETC               VARCHAR2(250 BYTE),
  PJT_PLACE         VARCHAR2(100 BYTE),
  CMP_REG_NO        VARCHAR2(10 BYTE),
  CONSTRAINT INSA_RECT_NOTICE_PK
  PRIMARY KEY
  (RECT_REG_NO)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE INSA
 DROP PRIMARY KEY CASCADE;

DROP TABLE INSA CASCADE CONSTRAINTS;

CREATE TABLE INSA
(
  SABUN           VARCHAR2(10 BYTE)             NOT NULL,
  JOIN_DAY        VARCHAR2(8 BYTE),
  RETIRE_DAY      VARCHAR2(8 BYTE),
  PUT_YN          VARCHAR2(1 BYTE),
  CLASS_GBN_CODE  VARCHAR2(3 BYTE),
  NAME            VARCHAR2(100 BYTE),
  REG_NO          VARCHAR2(13 BYTE),
  ENG_NAME        VARCHAR2(100 BYTE),
  PHONE           VARCHAR2(25 BYTE),
  HP              VARCHAR2(25 BYTE),
  CARRIER         VARCHAR2(500 BYTE),
  POS_GBN_CODE    VARCHAR2(5 BYTE),
  CMP_REG_NO      VARCHAR2(10 BYTE),
  SEX             VARCHAR2(1 BYTE),
  YEARS           NUMBER,
  EMAIL           VARCHAR2(50 BYTE),
  ZIP             VARCHAR2(6 BYTE),
  ADDR1           VARCHAR2(250 BYTE),
  ADDR2           VARCHAR2(250 BYTE),
  MIL_YN          VARCHAR2(10 BYTE),
  HOME_PHONE      VARCHAR2(25 BYTE),
  JOIN_GBN_CODE   VARCHAR2(3 BYTE),
  SALARY          NUMBER                        DEFAULT 0,
  KOSA_REG_YN     VARCHAR2(1 BYTE),
  KOSA_CLASS      VARCHAR2(3 BYTE),
  PW              VARCHAR2(15 BYTE),
  CONSTRAINT INSA_PK
  PRIMARY KEY
  (SABUN)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

DROP TABLE CHAPTER_1 CASCADE CONSTRAINTS;

CREATE TABLE CHAPTER_1
(
  SABUN     VARCHAR2(10 BYTE),
  NAME      VARCHAR2(50 BYTE),
  AGE       NUMBER,
  PHONE     VARCHAR2(15 BYTE),
  JOIN_DAY  VARCHAR2(8 BYTE)
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE TABLE_1 CASCADE CONSTRAINTS;

CREATE TABLE TABLE_1
(
  SABUN  CHAR(8 BYTE),
  NAME   CHAR(6 BYTE),
  AGE    CHAR(2 BYTE),
  PHONE  CHAR(11 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE A_PGM_AUTH
 DROP PRIMARY KEY CASCADE;

DROP TABLE A_PGM_AUTH CASCADE CONSTRAINTS;

CREATE TABLE A_PGM_AUTH
(
  ROLE_CD       VARCHAR2(2 BYTE)                NOT NULL,
  PGM_ID        VARCHAR2(20 BYTE)               NOT NULL,
  AUTHORITY_GB  VARCHAR2(1 BYTE)                NOT NULL,
  CONSTRAINT IDX00_PK_POR_VOC_PGM_AUTH
  PRIMARY KEY
  (ROLE_CD, PGM_ID)
  ENABLE VALIDATE
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    60
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE A_ADMIN_REG
 DROP PRIMARY KEY CASCADE;

DROP TABLE A_ADMIN_REG CASCADE CONSTRAINTS;

CREATE TABLE A_ADMIN_REG
(
  EMP_NO     VARCHAR2(9 BYTE)                   NOT NULL,
  CHARGE_GB  VARCHAR2(1 BYTE)                   NOT NULL,
  ROLE_CD    VARCHAR2(2 BYTE)                   NOT NULL,
  ORGAN      VARCHAR2(20 BYTE)                  NOT NULL,
  DEPT       VARCHAR2(20 BYTE)                  NOT NULL,
  CONSTRAINT IDX00_PK_POR_VOC_ADMIN_REG
  PRIMARY KEY
  (EMP_NO)
  ENABLE VALIDATE
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    60
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE A_MENU_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE A_MENU_LIST CASCADE CONSTRAINTS;

CREATE TABLE A_MENU_LIST
(
  MENU_ID           VARCHAR2(20 BYTE)           NOT NULL,
  MENU_NAME         VARCHAR2(100 BYTE)          NOT NULL,
  GENERIC_USE_GB    VARCHAR2(1 BYTE),
  MENU_DESCRIPTION  VARCHAR2(200 BYTE),
  UPPER_MENU_ID     VARCHAR2(20 BYTE),
  MENU_CREATE_DATE  DATE                        NOT NULL,
  CONSTRAINT IDX00_PK_POR_VOC_MENU_LIST
  PRIMARY KEY
  (MENU_ID)
  ENABLE VALIDATE
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    60
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE A_MENU_PGM
 DROP PRIMARY KEY CASCADE;

DROP TABLE A_MENU_PGM CASCADE CONSTRAINTS;

CREATE TABLE A_MENU_PGM
(
  MENU_ID      VARCHAR2(20 BYTE)                NOT NULL,
  PGM_ID       VARCHAR2(20 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(200 BYTE),
  CONSTRAINT IDX00_PK_POR_VOC_MENU_PGM
  PRIMARY KEY
  (MENU_ID, PGM_ID)
  ENABLE VALIDATE
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    60
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE A_PGM_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE A_PGM_LIST CASCADE CONSTRAINTS;

CREATE TABLE A_PGM_LIST
(
  PGM_ID           VARCHAR2(20 BYTE)            NOT NULL,
  PGM_NAME         VARCHAR2(100 BYTE),
  PGM_URL          VARCHAR2(100 BYTE),
  PGM_DESCRIPTION  VARCHAR2(100 BYTE),
  PGM_CREATE_DATE  DATE,
  FULL_PGM_NAME    VARCHAR2(100 BYTE),
  MENU_PGM_YN      VARCHAR2(1 BYTE),
  WEB_INF_ACTION   VARCHAR2(100 BYTE),
  CONSTRAINT IDX00_PK_POR_VOC_PGM_LIST
  PRIMARY KEY
  (PGM_ID)
  ENABLE VALIDATE
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    60
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE A_ROLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE A_ROLE CASCADE CONSTRAINTS;

CREATE TABLE A_ROLE
(
  ROLE_CD      VARCHAR2(2 BYTE)                 NOT NULL,
  ROLE_NAME    VARCHAR2(100 BYTE)               NOT NULL,
  DESCRIPTION  VARCHAR2(200 BYTE),
  CONSTRAINT IDX00_PK_POR_VOC_ROLE
  PRIMARY KEY
  (ROLE_CD)
  ENABLE VALIDATE
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    60
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE INSA_BBS
 DROP PRIMARY KEY CASCADE;

DROP TABLE INSA_BBS CASCADE CONSTRAINTS;

CREATE TABLE INSA_BBS
(
  BBS_CODE  VARCHAR2(8 BYTE)                    NOT NULL,
  BBS_SEQ   NUMBER                              NOT NULL,
  TITLE     VARCHAR2(100 BYTE),
  CONTENT   VARCHAR2(4000 BYTE),
  ID        VARCHAR2(10 BYTE),
  PW        VARCHAR2(10 BYTE),
  BBS_DATE  DATE,
  HIT_CNT   VARCHAR2(50 BYTE),
  CONSTRAINT INSA_BBS_PK
  PRIMARY KEY
  (BBS_CODE, BBS_SEQ)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE CMM_CODE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CMM_CODE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE CMM_CODE_DETAIL
(
  CLASS_CODE         VARCHAR2(3 BYTE)           NOT NULL,
  CODE_NO            VARCHAR2(6 BYTE)           NOT NULL,
  CODE_NAME          VARCHAR2(200 BYTE),
  CODE_NAME2         VARCHAR2(500 BYTE),
  CODE_ENG_NAME      VARCHAR2(100 BYTE),
  ETC_CODE1          VARCHAR2(100 BYTE),
  ETC_CODE2          VARCHAR2(100 BYTE),
  CODE_DESC          VARCHAR2(2000 BYTE),
  USE_YN             VARCHAR2(1 BYTE)           NOT NULL,
  SORT_SEQ           NUMBER,
  REGIST_TIME        DATE                       NOT NULL,
  REGIST_ID          VARCHAR2(10 BYTE)          NOT NULL,
  UPDATE_TIME        DATE                       NOT NULL,
  UPDATE_ID          VARCHAR2(8 BYTE)           NOT NULL,
  LAST_MODY_TIME     DATE                       NOT NULL,
  HIGHER_CLASS_CODE  VARCHAR2(3 BYTE),
  HIGHER_CODE_NO     VARCHAR2(6 BYTE),
  CONSTRAINT CMM_CODE_DETAIL_PK
  PRIMARY KEY
  (CLASS_CODE, CODE_NO)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE CMM_CODE_MASTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE CMM_CODE_MASTER CASCADE CONSTRAINTS;

CREATE TABLE CMM_CODE_MASTER
(
  CLASS_CODE   VARCHAR2(3 BYTE)                 NOT NULL,
  CLASS_NAME   VARCHAR2(50 BYTE)                NOT NULL,
  CLASS_LEN    NUMBER(2)                        NOT NULL,
  USE_YN       VARCHAR2(1 BYTE)                 NOT NULL,
  MAIN_TABLE   VARCHAR2(30 BYTE),
  MAIN_COLUMN  VARCHAR2(30 BYTE),
  CLASS_DESC   VARCHAR2(500 BYTE),
  REGIST_TIME  DATE                             NOT NULL,
  REGIST_ID    VARCHAR2(10 BYTE)                NOT NULL,
  CONSTRAINT CMM_CODE_MASTER_PK
  PRIMARY KEY
  (CLASS_CODE)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE INSA_COMPANY
 DROP PRIMARY KEY CASCADE;

DROP TABLE INSA_COMPANY CASCADE CONSTRAINTS;

CREATE TABLE INSA_COMPANY
(
  CMP_REG_NO        VARCHAR2(10 BYTE)           NOT NULL,
  CMP_NAME          VARCHAR2(100 BYTE),
  CMP_PHONE         VARCHAR2(100 BYTE),
  CMP_URL           VARCHAR2(100 BYTE),
  CMP_ZIP           VARCHAR2(7 BYTE),
  CMP_ADDR1         VARCHAR2(200 BYTE),
  CMP_ADDR2         VARCHAR2(200 BYTE),
  CMP_REL           VARCHAR2(250 BYTE),
  PRES_NAME         VARCHAR2(100 BYTE),
  PRES_PHONE        VARCHAR2(100 BYTE),
  PRES_HP           VARCHAR2(100 BYTE),
  PRES_MAIL         VARCHAR2(100 BYTE),
  SALE_COMPT_NAME   VARCHAR2(100 BYTE),
  SALE_COMPT_PHONE  VARCHAR2(100 BYTE),
  SALE_COMPT_HP     VARCHAR2(100 BYTE),
  SALE_COMPT_MAIL   VARCHAR2(100 BYTE),
  TAX_COMPT_NAME    VARCHAR2(100 BYTE),
  TAX_COMPT_PHONE   VARCHAR2(100 BYTE),
  TAX_COMPT_HP      VARCHAR2(100 BYTE),
  TAX_COMPT_MAIL    VARCHAR2(100 BYTE),
  REMARK            VARCHAR2(250 BYTE),
  DIS_YN            CHAR(1 BYTE),
  CMP_KIND          VARCHAR2(300 BYTE),
  FILE_SEQ          NUMBER,
  FILE_NAME         VARCHAR2(100 BYTE),
  PER_KIND          VARCHAR2(2 BYTE),
  CONSTRAINT INSA_COMPANY_PK
  PRIMARY KEY
  (CMP_REG_NO)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE DATA_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DATA_TYPE CASCADE CONSTRAINTS;

CREATE TABLE DATA_TYPE
(
  DT_SEQ        VARCHAR2(2 BYTE)                NOT NULL,
  DT_CHAR       CHAR(100 BYTE),
  DT_VARCHAR2   VARCHAR2(100 BYTE),
  DT_LONG       LONG,
  DT_NUMBER_1   NUMBER,
  DT_NUMBER_2   NUMBER(9,2),
  DT_DATE       DATE,
  DT_TIMESTAMP  TIMESTAMP(6),
  DT_BLOB       BLOB,
  DT_CLOB       CLOB,
  CONSTRAINT DATA_TYPE_PK
  PRIMARY KEY
  (DT_SEQ)
  ENABLE VALIDATE
)
LOB (DT_BLOB) STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
LOB (DT_CLOB) STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



DROP TABLE TEST_3 CASCADE CONSTRAINTS;

CREATE TABLE TEST_3
(
  EMPID_2    CHAR(8 BYTE),
  MGR        CHAR(2 BYTE),
  IMSI_DATE  DATE
)
TABLESPACE SYSTEM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE INSA_ACAD_ABILITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE INSA_ACAD_ABILITY CASCADE CONSTRAINTS;

CREATE TABLE INSA_ACAD_ABILITY
(
  SABUN            VARCHAR2(10 BYTE)            NOT NULL,
  SEQ              NUMBER                       NOT NULL,
  MAJOR_STUDY_GBN  VARCHAR2(100 BYTE),
  GRAT_YN          VARCHAR2(1 BYTE),
  GRAT_YEAR        VARCHAR2(4 BYTE),
  GRAT_MONTH       VARCHAR2(2 BYTE),
  SCHOOL_NAME      VARCHAR2(50 BYTE),
  CONSTRAINT PK_INSA_ACAD_ABILITY
  PRIMARY KEY
  (SABUN, SEQ)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE INSA_EMP_PJT
 DROP PRIMARY KEY CASCADE;

DROP TABLE INSA_EMP_PJT CASCADE CONSTRAINTS;

CREATE TABLE INSA_EMP_PJT
(
  RECT_REG_NO      VARCHAR2(5 BYTE)             NOT NULL,
  SABUN            VARCHAR2(10 BYTE)            NOT NULL,
  PUT_START_DAY    DATE,
  PUT_END_DAY      DATE,
  PROG_STATE_CODE  VARCHAR2(3 BYTE),
  REG_DAY          VARCHAR2(8 BYTE),
  CONSTRAINT INSA_EMP_PJT_PK
  PRIMARY KEY
  (RECT_REG_NO, SABUN)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE TEST_1
 DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_1 CASCADE CONSTRAINTS;

CREATE TABLE TEST_1
(
  NO  VARCHAR2(10 BYTE),
  PRIMARY KEY
  (NO)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE TEST_2
 DROP PRIMARY KEY CASCADE;

DROP TABLE TEST_2 CASCADE CONSTRAINTS;

CREATE TABLE TEST_2
(
  SABUN  VARCHAR2(10 BYTE),
  PRIMARY KEY
  (SABUN)
  ENABLE VALIDATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE "년월일집계" CASCADE CONSTRAINTS;

CREATE TABLE "년월일집계"
(
  "거래처코드"  CHAR(6 BYTE),
  "발행년월일"  CHAR(8 BYTE),
  "입출구분"   CHAR(1 BYTE),
  "금액"     NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



DROP TABLE "전표" CASCADE CONSTRAINTS;

CREATE TABLE "전표"
(
  "전표번호"   NUMBER,
  "거래처코드"  CHAR(6 BYTE),
  "입출구분"   CHAR(1 BYTE),
  "금액"     NUMBER,
  "발행인"    CHAR(6 BYTE),
  "발행일시"   DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TEST.TABLE_2 MODIFY (ACAD_ABILITY CHAR (6));
ALTER TABLE TEST.TABLE_3 MODIFY (ACAD_ABILITY CHAR (6));
ALTER TABLE TEST.TABLE_2 MODIFY (MAJOR_STUDY VARCHAR2 (20));
ALTER TABLE TEST.TABLE_1 MODIFY (NAME CHAR (15));
ALTER TABLE TEST.A_PGM_LIST MODIFY (PGM_DESCRIPTION CHAR (150));
ALTER TABLE TEST.DATA_TYPE MODIFY (DT_CHAR CHAR (150));
ALTER TABLE TEST.전표 MODIFY (발행인 CHAR (9));